### ISSUE TITLE
Error: Invalid debug adapter

### ISSUE THREAD

**Issue by rubensa** [firefox-devtools/vscode-firefox-debug#370]
### Environment:

- **Ubuntu 22.04.5 LTS**
- **Firefox 132.0** (installed as a deb package from Mozilla repos, not as snap package from Ubuntu repos)
- **VSCode 1.95.0**
- **Debugger for Firefox v2.9.10**

Running using **VSCode Devcontainers** on Ubuntu Docker container ([remote development](https://code.visualstudio.com/docs/remote/remote-overview)).

### The problem:

If I set breakpoints in **VSCode** on a **TypeScript** file (**Angular** app) the browser does not stop on it.

### The log:

On **VSCode Developer Tools** console I can see the following error:

>   ERR Invalid debug adapter: Error: Invalid debug adapter
    at b4t.p (vscode-file://vscode-app/opt/VSCode-linux-x64-1.95.0/resources/app/out/vs/workbench/workbench.desktop.main.js:615:95)
    at b4t.$acceptDAExit (vscode-file://vscode-app/opt/VSCode-linux-x64-1.95.0/resources/app/out/vs/workbench/workbench.desktop.main.js:615:35)
    at Pht.S (vscode-file://vscode-app/opt/VSCode-linux-x64-1.95.0/resources/app/out/vs/workbench/workbench.desktop.main.js:3124:41686)
    at Pht.Q (vscode-file://vscode-app/opt/VSCode-linux-x64-1.95.0/resources/app/out/vs/workbench/workbench.desktop.main.js:3124:41464)
    at Pht.M (vscode-file://vscode-app/opt/VSCode-linux-x64-1.95.0/resources/app/out/vs/workbench/workbench.desktop.main.js:3124:40552)
    at Pht.L (vscode-file://vscode-app/opt/VSCode-linux-x64-1.95.0/resources/app/out/vs/workbench/workbench.desktop.main.js:3124:39789)
    at vZ.value (vscode-file://vscode-app/opt/VSCode-linux-x64-1.95.0/resources/app/out/vs/workbench/workbench.desktop.main.js:3124:38450)
    at x.B (vscode-file://vscode-app/opt/VSCode-linux-x64-1.95.0/resources/app/out/vs/workbench/workbench.desktop.main.js:30:747)
    at x.fire (vscode-file://vscode-app/opt/VSCode-linux-x64-1.95.0/resources/app/out/vs/workbench/workbench.desktop.main.js:30:965)
    at L6.fire (vscode-file://vscode-app/opt/VSCode-linux-x64-1.95.0/resources/app/out/vs/workbench/workbench.desktop.main.js:630:10348)

### Detailed info:

If I open the **Firefox Web Developer Tools** there seems to be no breakpoints set.

If I add a breakpoint in **VSCode** I can see something like this in the log:

> DEBUG|236.222|BreakpointsManager: Setting 1 breakpoints for vscode-remote://dev-container%2B7b22686f737450617468223...227d7d/workspaces/app/module/src/modules/module/pages/page/page.page.ts

but the breakpoint does not appear on **Firefox Web Developer Tools**. When this breakpoint should be reached Firefox does not stops execution.

If I add a breakpoint on **Firefox Web Developer Tools** I can't see any notification sent to the server for the new break point in the log.  When this breakpoint is reached Firefox stops execution there but it can be debugged only on **Firefox Web Developer Tools** not on VSCode.

**Comment by rubensa** [comment]
This seems to have been fixed on **VSCode 1.95.2**. See: https://github.com/microsoft/vscode/issues/232730

**Comment by rubensa** [comment]
Too fast...  Still not working.  Same behavior as already stated.

**Comment by hbenl** [comment]
Thanks for linking to the upstream issue. That issue and its duplicates (microsoft/vscode#232651 links to many of those) have been closed but many users are reporting that the issue still isn't fixed.

**Comment by rubensa** [comment]
@hbenl In my case the Chrome issue is fixed but the Firefox issue not.

The different here is that in case of Chrome, the browser is installed inside the Docker dev container but in case of Firefox it is on the host.

The pointed upstream issues are about Chrome freeze when there are breakpoints set and the one reported here is about Firefox not stopping at any breakpoint set in VSCode (when using a Docker devcontainer).

**Comment by hbenl** [comment]
> In my case the Chrome issue is fixed but the Firefox issue not.

Hmm, so maybe these are different issues after all. Unfortunately I couldn't reproduce this, have you tried with VS Code 1.94?

**Comment by rubensa** [comment]
@hbenl Tried with 1.94 (rebuilding the container as I found extension incompatibilities on VSCode version downgrade) with same results.

In the meantime I also tried with Microsoft Edge in the host and is working as expected.  So only Firefox does not stop on breakpoints.

_NOTE_: I'll say that I'm working in a legacy Ruby on Rails app with an Angular frontend build with Ionic using Gulp.

**Comment by hbenl** [comment]
So this issue is actually unrelated to microsoft/vscode#232730 (because that issue only appeared in 1.95).
- when you set the breakpoint in VS Code during a debug session, does it get verified (i.e. does it turn red or does it stay grey)?
- when you reload the app in Firefox after setting the breakpoint (i.e. press F5 or the reload button in Firefox), do you then hit the breakpoint?
- could you paste the complete logs of a debug session (in this issue or in a gist)?

Some notes:
- I think the error "Invalid debug adapter", which is coming from VS Code (not from this extension) is also unrelated, otherwise you'd probably be unable to start a debug session at all
- it's normal that breakpoints set in Firefox DevTools do not show up in VS Code and vice versa, Firefox keeps those separate
- furthermore, when you hit a breakpoint set in Firefox DevTools, you won't see the pause information (i.e. the location where you're paused and the frames and scopes) in VS Code and vice versa

**Comment by rubensa** [comment]
- When I set a breakpoint in VSCode it turns red.
- Despite reloading the page, the breakpoint is not hit.  Only breakpoints set in Ruby code are hit (but none set on TypeScript code).
- I attached a [vscode-firefox-debug-session.log](https://github.com/user-attachments/files/17771614/vscode-firefox-debug-session.log) (with some manual modifications for sensitive information, mainly OAuth2 related).

Thanks for the info about how Firefox and VS Code debug works.

**Comment by hbenl** [comment]
This line in the log shows the problem:
```
DEBUG|021.029|SourceMappingThreadActorProxy: Trying to sourcemap {"actor":"server1.conn0.child9/source24","extensionName":null,"url":"http://my-app.local.computer:3000/admin/login","isBlackBoxed":false,"sourceMapBaseURL":"http://my-app.local.computer:3000/admin/login","sourceMapURL":null,"introductionType":"scriptElement","isInlineSource":true,"sourceStartLine":1,"sourceStartColumn":249,"sourceLength":70}
```
The extension is checking if it should sourcemap `http://my-app.local.computer:3000/admin/login` but that source apparently doesn't contain a `//# sourceMappingURL=...` comment (the log message says `"sourceMapURL":null`), so it can't find a sourcemap for it.

From the log I can see that you set the breakpoints before starting the debugging session (the log file starts with messages from `BreakpointsManager` listing the files where breakpoints were set when the session started). In that case the breakpoints in the Typescript file will be red but they should turn grey when you start the debugging session and they should remain grey for the entire duration of that session because according to the log file, they are never sent to Firefox (due to the missing sourcemap) and hence never get verified in VS Code.

But without sourcemaps you shouldn't be able to see the original files (like `my-app/frontend/src/modules/master-data/pages/md-categories/md-categories.page.ts`, where you set the breakpoint) in Firefox DevTools either.

**Comment by rubensa** [comment]
Thanks for investigating @hbenl 

Yes, the endpoint was set before but it keeps red on debugging session.  I can add new ones or remove existing ones while on debugging session and the new ones keep being red.

The page `http://my-app.local.computer:3000/admin/login` issues a redirect to the oauth login system so there is no sourcemap but `http://my-app.local.computer:3000/app/categories/` should have.

**Comment by crossan007** [comment]
This also seems to completely freeze VSCode with some combination of hitting a breakpoint with a broken mapping and hitting "resume":

```
ERROR|512.443|ThreadCoordinator: resume failed: Error: Error parsing mappings (code 1): the mappings contained a negative line, column, source index, or name index
DEBUG|512.443|ThreadPauseCoordinator: Resuming Tab 1 failed
DEBUG|512.443|ThreadCoordinator: state: paused, target: running, tasks: 0/0, eval: 0
DEBUG|512.443|ThreadPauseCoordinator: Requesting resume for Tab 1
DEBUG|512.443|ThreadPauseCoordinator: current pauses: [Tab 1/user], requested pauses: [], requested resumes: [Tab 1]
DEBUG|512.443|ThreadPauseCoordinator: Resuming Tab 1
ERROR|512.443|ThreadCoordinator: resume failed: Error: Error parsing mappings (code 1): the mappings contained a negative line, column, source index, or name index
DEBUG|512.444|ThreadPauseCoordinator: Resuming Tab 1 failed
DEBUG|512.444|ThreadCoordinator: state: paused, target: running, tasks: 0/0, eval: 0
DEBUG|512.444|ThreadPauseCoordinator: Requesting resume for Tab 1
DEBUG|512.444|ThreadPauseCoordinator: current pauses: [Tab 1/user], requested pauses: [], requested resumes: [Tab 1]
DEBUG|512.444|ThreadPauseCoordinator: Resuming Tab 1
...
## Repeated log spam of these lines; until I finally force-closed VSCode
...
ERROR|575.583|ThreadCoordinator: resume failed: Error: Error parsing mappings (code 1): the mappings contained a negative line, column, source index, or name index
DEBUG|575.583|ThreadPauseCoordinator: Resuming Tab 1 failed
DEBUG|575.583|ThreadCoordinator: state: paused, target: running, tasks: 0/0, eval: 0
```

**Comment by crossan007** [comment]
It seems like the error 

> WARN |009.663|ThreadCoordinator: task running on paused thread failed: Error: Error parsing mappings (code 1): the mappings contained a negative line, column, source index, or name index

is being caught in [executeOnPausedThread](https://github.com/firefox-devtools/vscode-firefox-debug/blob/9ac8417d1a9ba0e55a001d883f7ba2f672ae2d1b/src/adapter/coordinator/thread.ts#L370) is thrown by [source-map BasicSourceMapConsumer._parseMappings](https://github.com/mozilla/source-map/blob/3cb92cc3b73bfab27c146bae4ef2bc09dbb4e5ed/lib/source-map-consumer.js#L324)

**Comment by crossan007** [comment]
Possibly Related: 
* https://github.com/microsoft/vscode/issues/232730
* https://github.com/microsoft/vscode/issues/232651#issuecomment-2465202370

Using the nightly VSCode JSDebugger doesn't seem to help: https://github.com/microsoft/vscode-js-debug/?tab=readme-ov-file#nightly-extension

**Comment by crossan007** [comment]
Setting a breakpoint inside of a `setInterval` callback started within the constructor of a `@Component` class works, but setting a breakpoint in a function of that same class which is called from the DOM causes the sourcemap error 🤔

**Comment by hbenl** [comment]
@rubensa Your issue should be fixed in version 2.10.0, the debugger should keep working after navigations.

@crossan007 If the extension fails to parse your sourcemap, I'm not surprised if breakpoints start failing. I'd need to take a look at the sourcemap to see why it fails - do you have a public project where this happens?

**Comment by rubensa** [comment]
@hbenl Just checked and it's working now.  Thank you so much!

**Comment by crossan007** [comment]
@hbenl I'm beginning to suspect that my issue is not with this debug plugin, but rather with Angular source map generation.  

I don't quite have a complete enough understanding of source maps; however, it seems that something in the Webpack bundling process is causing lazily loaded Angular modules to fail to match a project source file.

My project is not public, and I can't really share the details publicly, but I appreciate the offer.

Thanks for humoring my (many) misguided comments on this issue.
