### ISSUE TITLE
Unverified breakpoints after 2.12.1 release

### ISSUE THREAD

**Issue by AnrDaemon** [firefox-devtools/vscode-firefox-debug#378]
Type: <b>Bug</b>

launch.json configuration:

```
{
            "log": {
                "fileLevel": {
                    "default": "Debug"
                },
                "fileName": "${workspaceFolder}/logs/ffdebug.log"
            },
            "name": "FFdebug",
            "pathMappings": [
                {
                    "path": "${workspaceFolder}/app/",
                    "url": "http://127.0.0.1:5500"
                },
                {
                    "path": "${workspaceFolder}/app/",
                    "url": "https://proto.example.com/"
                },
                {
                    "path": "${workspaceFolder}/app/",
                    "url": "https://stage.example.com/"
                }
            ],
            "preLaunchTask": "Firefox debugger",
            "request": "attach",
            "skipFiles": [
                "**/js.stripe.com/**/*",
                "**/static.sumsub.com/**/*",
                "**/node_modules/**/*",
                "**/*.min.js",
                "${workspaceFolder}/app/lib/tools.js"
            ],
            "host": "127.0.0.1",
            "type": "firefox"
        }
```

After upgrading to 2.12.1 release and restarting the debugger, I'm unable to verify any of the breakpoints. I have tried to restart both the IDE and the browser to get it to work, but then it would catch a breakpoint in the newly opened tab and don't show it in the IDE.
I have to close all tabs in the browser but one and restart the debugger to connect it again.

Extension version: 2.12.1
VS Code version: Code 1.96.2 (fabdb6a30b49f79a7aba0f2ad9df9b399473380f, 2024-12-19T10:22:47.216Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8145U CPU @ 2.10GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.86GB (0.24GB free)|
|Process Argv|--folder-uri file:///d%3A/Profiles/anrdaemon/Documents/hk/invapi-php|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by hbenl** [comment]
This could be caused by a bug that I just fixed in version 2.13.0. Could you retry with that version?

**Comment by AnrDaemon** [comment]
Tested, not fixed. To shed a little more light (I don't think that's relevant, but just in case):
The application uses custom click handlers over internal protocol prefixes (like `<a href="smth:ID"> … </a>` will open the entity `smth` with specified ID, the ctrl/middle click will `window.open()` a specific URL with GET params (like, `http://example.com/?entity=smth&id=ID`). There's the problem starts.
The log shows that breakpoints are recognized, the browser will correctly stop at the breakpoints, but IDE will not show the interface, and it still shows the ghost tabs in threads list.

Restarting the debugger in the IDE may help to revive the system. Or not. Or in the last try it outright forgot that we're debugging and breakpoints ceased to work.

Had to reduce tabs to one again to make it behave.

**Comment by hbenl** [comment]
Which version of Firefox do you use? I've noticed a [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1941027) in the current Developer and Nightly editions that could cause this. If you've used one of those, try with the stable edition and tell me if that works better.

**Comment by hbenl** [comment]
OK, so this is a different issue. Could you share your `logs/ffdebug.log`?

**Comment by AnrDaemon** [comment]
I'll have to try and reproduce it with a safe data. Will take a day or two. Sorry for delays.

**Comment by AnrDaemon** [comment]
I think I understand the tripping point.

When I start to open and close a lot of tabs with `window.open` like

```js
            return void window.open(window.location.origin + window.location.pathname + `?${link.proto}:${link.href}`);
```

either FF itself or the extension lose its mind and produce results like

![Image](https://github.com/user-attachments/assets/3da2a00c-8ade-4327-9f61-2b86cb97e5af)

Note that it correctly recognize that only 3 tabs are open, but shows a lot of sessions. This is after debugger reload.

**Comment by hbenl** [comment]
Those extra threads (with `undefined` URL) are for WebExtensions - in the latest version of this extension (2.14.1) they will not show up anymore (unless your launch configuration specifies a WebExtension to debug).
But I don't think that is the cause of this issue, I think it is caused by a [Firefox issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1941027) that seems to have a bigger impact than I initially thought. We're currently discussing how to fix this issue.

**Comment by AnrDaemon** [comment]
It says it is 135 latest right now. Will wait a few days to report.

**Comment by hbenl** [comment]
> It says it is 135 latest right now.

Yes, the stable edition will go to version 137 [next month](https://whattrainisitnow.com/calendar/). If you want to test the fix earlier than that you'll need to install the [Nightly edition](https://www.mozilla.org/en-US/firefox/channel/desktop/).

**Comment by AnrDaemon** [comment]
Damn, that's long wait. Will have to put it on the calendar. I don't have time to play with nightlies.

**Comment by AnrDaemon** [comment]
Doesn't seems to have been fixed with 137 release. If I have two tabs open, and they contain slightly different runtime, it's a big "if", if the right breakpoint will be set in the browser. I still have to close all other tabs and reload the debugger to get it to senses.
